#%RAML 1.0 NamedExample
[{
                "id": 101,
                "title": "API",
                "content": "an API application programming interface",
                "createdAt": "2020-11-10T13:44:12.283-08:00",
                "updatedAt" : "2020-11-10T13:44:12.283-08:00"

              },
              {
                "id": 102,
                "title": "API",
                "content": "an API application programming interface",
                "createdAt": "2020-11-10T13:44:12.283-08:00",
                "updatedAt" : "2020-11-10T13:44:12.283-08:00"

              }]